version: '3.8'
services:
    riak:
        build: ./docker-riak/
        ports:
            - "0.0.0.0:8098:8098"
    dynamodb-local:
        command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./"
        image: "amazon/dynamodb-local:latest"
        container_name: dynamodb-local
        working_dir: /home/dynamodblocal
    app:
        build:
            context: .
            dockerfile: docker-app/Dockerfile
        environment:
            AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
            AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
            AWS_DEFAULT_REGION: 'eu-west-2'
            DYNAMO_ENDPOINT_URL: 'http://dynamodb-local:8000'
            RIAK_HOST: 'riak'
        depends_on:
            - riak
            - dynamodb-local
